<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C40LAP-10296" ignored="0" name="ErrorValidation" tests="2" failures="1" timestamp="2023-07-05T16:44:51 IST" time="26.656" errors="0">
  <testcase name="createOrder" time="1.366" classname="Organization.Ecommerce.EcommerceBase">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully] but found []">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found []
at Organization.Ecommerce.EcommerceBase.createOrder(EcommerceBase.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- createOrder -->
  <testcase name="createOrder" time="7.033" classname="Organization.Ecommerce.EcommerceBase"/>
</testsuite> <!-- ErrorValidation -->
